Repository PagelsR-Sandbox/clevelandcliffs-2024-07-23, pull requests merged in 2024-07, with the labels that each got.

#12 Updated my slide
  _slides/02-PagelsR.md
Labels: documentation

#16 LOREM IPSUM
  _slides/jruan.md
Labels: good first issue

#13 Slide for Richard Stump
  _slides/07-Richard-Stump.md
Labels: enhancement

#18 Updated caption on my slide
  _slides/12-jimmielyon.md
Labels: documentation
